export default function Title() {
  return (
    <div className="title">
      <div>
        <img src="AlexProf-logo-1.jpg" alt="AlexProf" className="logo" />
        <h1 className="pagetitle">AlexProf services</h1>
      </div>
      <div>
        <img
          className="social"
          width="48"
          height="48"
          src="https://img.icons8.com/color/48/instagram-new--v2.png"
          alt="instagram-new--v2"
        />
        <img
          className="social"
          width="48"
          height="48"
          src="https://img.icons8.com/pulsar-line/48/threads.png"
          alt="threads"
        />
        <img
          className="social"
          width="48"
          height="48"
          src="https://img.icons8.com/color/48/twitterx--v1.png"
          alt="twitterx--v1"
        />
        <img
          className="social"
          width="48"
          height="48"
          src="https://img.icons8.com/color/48/facebook-new.png"
          alt="facebook-new"
        />
        <a href="https://discord.gg/2sUr3M6WPS" target="_blank">
          <img
            className="social"
            width="48"
            height="48"
            src="https://img.icons8.com/color/48/discord-logo.png"
            alt="discord-logo"
          />
        </a>
        <img
          className="social"
          width="48"
          height="48"
          src="https://img.icons8.com/sf-regular-filled/48/medium-logo.png"
          alt="medium-logo"
        />
        <img
          className="social"
          width="48"
          height="48"
          src="https://img.icons8.com/color/48/youtube-squared.png"
          alt="youtube-squared"
        />
        <img
          className="social"
          width="48"
          height="48"
          src="https://img.icons8.com/color/48/tiktok--v1.png"
          alt="tiktok--v1"
        />
      </div>
    </div>
  );
}
